/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author marlon
 */
public class InicialGUI extends javax.swing.JFrame {

    /**
     * Creates new form InicialGUI
     */
    public InicialGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMBMenu = new javax.swing.JMenuBar();
        jMCadastrar = new javax.swing.JMenu();
        jMICadCliente = new javax.swing.JMenuItem();
        jMICadImovel = new javax.swing.JMenuItem();
        jMICadUsuario = new javax.swing.JMenuItem();
        jMConsultar = new javax.swing.JMenu();
        jMIConsCliente = new javax.swing.JMenuItem();
        jMIConsImovel = new javax.swing.JMenuItem();
        jMIConsUsuario = new javax.swing.JMenuItem();
        jMAcoes = new javax.swing.JMenu();
        jMIAlugar = new javax.swing.JMenuItem();
        jMIVender = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMIAjuda = new javax.swing.JMenuItem();
        jMISobre = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(177, 90, 90));

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        jLUsuario.setText("jLUsuarioLogado");

        jLabel1.setText("Data e Hora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLUsuario)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/fearSoft.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Imobiliaria.png"))); // NOI18N

        jMCadastrar.setText("Cadastrar");

        jMICadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/people.png"))); // NOI18N
        jMICadCliente.setText("Cliente");
        jMICadCliente.setToolTipText("Clique aqui para cadastrar cliente");
        jMCadastrar.add(jMICadCliente);

        jMICadImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/home.png"))); // NOI18N
        jMICadImovel.setText("Imóvel");
        jMICadImovel.setToolTipText("Clique aqui para cadastrar imóvel");
        jMCadastrar.add(jMICadImovel);

        jMICadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/man_brown.png"))); // NOI18N
        jMICadUsuario.setText("Usuário");
        jMICadUsuario.setToolTipText("Clique aqui para cadastrar usuário");
        jMCadastrar.add(jMICadUsuario);

        jMBMenu.add(jMCadastrar);

        jMConsultar.setText("Consultar");

        jMIConsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Search.png"))); // NOI18N
        jMIConsCliente.setText("Cliente");
        jMConsultar.add(jMIConsCliente);

        jMIConsImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Search.png"))); // NOI18N
        jMIConsImovel.setText("Imóvel");
        jMConsultar.add(jMIConsImovel);

        jMIConsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Search.png"))); // NOI18N
        jMIConsUsuario.setText("Usuário");
        jMConsultar.add(jMIConsUsuario);

        jMBMenu.add(jMConsultar);

        jMAcoes.setText("Ações");

        jMIAlugar.setText("Alugar Imóvel");
        jMAcoes.add(jMIAlugar);

        jMIVender.setText("Vender Imóvel");
        jMAcoes.add(jMIVender);

        jMBMenu.add(jMAcoes);

        jMAjuda.setText("Ajuda");

        jMIAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/emblem_library.png"))); // NOI18N
        jMIAjuda.setText("Ajuda");
        jMAjuda.add(jMIAjuda);

        jMISobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/dialog_question.png"))); // NOI18N
        jMISobre.setText("Sobre");
        jMAjuda.add(jMISobre);

        jMBMenu.add(jMAjuda);

        setJMenuBar(jMBMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel3)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMAcoes;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenu jMCadastrar;
    private javax.swing.JMenu jMConsultar;
    private javax.swing.JMenuItem jMIAjuda;
    private javax.swing.JMenuItem jMIAlugar;
    private javax.swing.JMenuItem jMICadCliente;
    private javax.swing.JMenuItem jMICadImovel;
    private javax.swing.JMenuItem jMICadUsuario;
    private javax.swing.JMenuItem jMIConsCliente;
    private javax.swing.JMenuItem jMIConsImovel;
    private javax.swing.JMenuItem jMIConsUsuario;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenuItem jMIVender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
