/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import control.UsuarioController;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author eder
 */
public class UsuarioView extends javax.swing.JDialog {

    /**
     * Creates new form UsuarioView
     */
    private UsuarioController usuarioController;

    public UsuarioView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.usuarioController = new UsuarioController();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jLNome = new javax.swing.JLabel();
        jLLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLCodigo = new javax.swing.JLabel();
        jLCodigo2 = new javax.swing.JLabel();

        setTitle("Dados de Usuário");

        jLabel1.setText("Nome:");

        jLabel2.setText("Login:");

        jBEditar.setText("Editar");
        jBEditar.setToolTipText("Editar Dados do Cadastro");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.setToolTipText("Salvar Dados e Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.setToolTipText("Excluir Cadastro de Usuário");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLNome.setForeground(new java.awt.Color(1, 1, 255));
        jLNome.setText("usuario");
        jLNome.setToolTipText("Nome do Usuário");

        jLLogin.setForeground(new java.awt.Color(0, 0, 255));
        jLLogin.setText("login");
        jLLogin.setToolTipText("Login");

        jLabel3.setText("Código:");

        jLCodigo2.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jBExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBEditar)
                .addGap(18, 18, 18)
                .addComponent(jBFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addComponent(jLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFechar)
                    .addComponent(jBEditar)
                    .addComponent(jBExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setValues(UsuarioController usuario) {
        this.usuarioController.setUsuario(usuario.getUsuario());
        
        jLCodigo2.setText(this.usuarioController.getUsuario().getId().toString());
        
        jLNome.setText(this.usuarioController.getUsuario().getNome());
        jLNome.setForeground(Color.blue);
        jLLogin.setText(this.usuarioController.getUsuario().getLogin());
        jLLogin.setForeground(Color.blue);
        
    }

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        UsuarioEditView editView = new UsuarioEditView(new Frame(), true);
        editView.setLocationRelativeTo(null);
        editView.setEdit(true);
        editView.setValues(usuarioController);
        dispose();
        editView.setVisible(true);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int pos = JOptionPane.showConfirmDialog(null, "Deseja Excluir Cadastro de Usuário?", "Exclusão de Cadastro", 2);
//        setValues();
        setValues(this.usuarioController);
        if (pos == 0) {
            if (this.usuarioController.getUsuario().getId() > 0) {
                try{
                    this.usuarioController.delete(this.usuarioController.getUsuario());
                    JOptionPane.showMessageDialog(null, "Usuário Excluído com Sucesso!");
                }catch(RuntimeException ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Excluir Usuário!","Erro",JOptionPane.ERROR_MESSAGE); 
                }                
            }
            dispose();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFechar;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLCodigo2;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
