/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import java.awt.Frame;
import javax.swing.JFrame;
import view.imovel.ImovelEditView;
import view.imovel.ImovelQueryView;
import view.imovel.ImovelView;
import view.usuario.UsuarioEditView;

/**
 *
 * @author eder
 */
public class Imobiliaria extends javax.swing.JDialog {

    /**
     * Creates new form Imobiliaria
     */
    
    public Imobiliaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsCliente = new javax.swing.JButton();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonCadImovel = new javax.swing.JButton();
        jButtonConsImovel = new javax.swing.JButton();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonConsUsuario = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jButtonLocar = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jLUsuarioLogado = new javax.swing.JLabel();
        jMenuBarTop = new javax.swing.JMenuBar();
        jMCliente = new javax.swing.JMenu();
        jMICadCliente = new javax.swing.JMenuItem();
        jMIConsCliente = new javax.swing.JMenuItem();
        jMImovel = new javax.swing.JMenu();
        jMICadImovel = new javax.swing.JMenuItem();
        jMIConsImovel = new javax.swing.JMenuItem();
        jMUsuario = new javax.swing.JMenu();
        jMICadUsuario = new javax.swing.JMenuItem();
        jMIConsUsuario = new javax.swing.JMenuItem();
        jMVenda = new javax.swing.JMenu();
        jMLocacao = new javax.swing.JMenu();
        jMAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonConsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jButtonConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsClienteActionPerformed(evt);
            }
        });

        jButtonCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jButtonCadCliente.setToolTipText("Cadastrar um Novo Cliente");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });

        jButtonCadImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jButtonCadImovel.setToolTipText("Cadastrar um Novo Imóvel");
        jButtonCadImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadImovelActionPerformed(evt);
            }
        });

        jButtonConsImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jButtonConsImovel.setToolTipText("Pesquisar Dados de Imóvel");
        jButtonConsImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsImovelActionPerformed(evt);
            }
        });

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Cadastrar um Novo Usuário");
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });

        jButtonConsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jButtonConsUsuario.setToolTipText("Pesquisar Dados de Usuário");
        jButtonConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsUsuarioActionPerformed(evt);
            }
        });

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dollars.png"))); // NOI18N
        jButtonVenda.setToolTipText("Vender Imóvel");
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });

        jButtonLocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contract.png"))); // NOI18N
        jButtonLocar.setToolTipText("Locar Imóvel");
        jButtonLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocarActionPerformed(evt);
            }
        });

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        jButtonAjuda.setToolTipText("Ajuda");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        jLUsuarioLogado.setToolTipText("Usuário Logado");

        jMCliente.setText("Cliente");
        jMCliente.setToolTipText("");

        jMICadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadCliente.setText("Cadastrar");
        jMICadCliente.setToolTipText("Cadastrar um Novo Cliente");
        jMICadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMICadCliente);

        jMIConsCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIConsCliente.setText("Pesquisar");
        jMIConsCliente.setToolTipText("Pesquisar Dados de Clientes");
        jMIConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMIConsCliente);

        jMenuBarTop.add(jMCliente);

        jMImovel.setText("Imóvel");

        jMICadImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadImovel.setText("Cadastrar");
        jMICadImovel.setToolTipText("Cadastrar um Novo Imóvel");
        jMICadImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadImovelActionPerformed(evt);
            }
        });
        jMImovel.add(jMICadImovel);

        jMIConsImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIConsImovel.setText("Pesquisar");
        jMIConsImovel.setToolTipText("Pesquisar Dados de Imóveis");
        jMIConsImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsImovelActionPerformed(evt);
            }
        });
        jMImovel.add(jMIConsImovel);

        jMenuBarTop.add(jMImovel);

        jMUsuario.setText("Usuário");

        jMICadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadUsuario.setText("Cadastro");
        jMICadUsuario.setToolTipText("Cadastrar um Novo Usuário");
        jMICadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadUsuarioActionPerformed(evt);
            }
        });
        jMUsuario.add(jMICadUsuario);

        jMIConsUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIConsUsuario.setText("Pesquisar");
        jMIConsUsuario.setToolTipText("Pesquisar Dados de Usuários");
        jMIConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsUsuarioActionPerformed(evt);
            }
        });
        jMUsuario.add(jMIConsUsuario);

        jMenuBarTop.add(jMUsuario);

        jMVenda.setText("Venda");
        jMenuBarTop.add(jMVenda);

        jMLocacao.setText("Locação");
        jMenuBarTop.add(jMLocacao);

        jMAjuda.setText("Ajuda");
        jMenuBarTop.add(jMAjuda);

        setJMenuBar(jMenuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonConsImovel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadImovel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonLocar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 455, Short.MAX_VALUE)
                .addComponent(jLUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cliente
    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsClienteActionPerformed
   
    //Imovel
    private void jButtonCadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadImovelActionPerformed
        // TODO add your handling code here:
        ImovelEditView editView = new ImovelEditView(new Frame(), true);
        editView.setLocationRelativeTo(null);
        editView.setVisible(true);
    }//GEN-LAST:event_jButtonCadImovelActionPerformed

    private void jButtonConsImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsImovelActionPerformed
        // TODO add your handling code here:
        ImovelQueryView imovelQueryView = new ImovelQueryView(new Frame(), true);
        imovelQueryView.setLocationRelativeTo(null);
        imovelQueryView.setVisible(true);
    }//GEN-LAST:event_jButtonConsImovelActionPerformed

    
    //Usuario
    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
        // TODO add your handling code here:
        cadastroUsuario();
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    private void jButtonConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsUsuarioActionPerformed

    
    //Venda
    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaActionPerformed

    
    //Locação
    private void jButtonLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLocarActionPerformed

    
    //Ajuda
    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    //Menu Cliente
    private void jMICadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICadClienteActionPerformed

    private void jMIConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIConsClienteActionPerformed

    
    //Menu Imovel
    private void jMICadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICadImovelActionPerformed

    private void jMIConsImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIConsImovelActionPerformed

    
    //Menu Usuario
    private void jMICadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICadUsuarioActionPerformed

    private void jMIConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIConsUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Imobiliaria dialog = new Imobiliaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                LoginView loginView = new LoginView(new JFrame(), true);
                dialog.setSize(800, 600);
                dialog.setVisible(false);

                loginView.setLocationRelativeTo(null);
                loginView.setVisible(true);
                if (LoginView.isLogin()) {
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonCadImovel;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonConsCliente;
    private javax.swing.JButton jButtonConsImovel;
    private javax.swing.JButton jButtonConsUsuario;
    private javax.swing.JButton jButtonLocar;
    private javax.swing.JButton jButtonVenda;
    protected static javax.swing.JLabel jLUsuarioLogado;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMICadCliente;
    private javax.swing.JMenuItem jMICadImovel;
    private javax.swing.JMenuItem jMICadUsuario;
    private javax.swing.JMenuItem jMIConsCliente;
    private javax.swing.JMenuItem jMIConsImovel;
    private javax.swing.JMenuItem jMIConsUsuario;
    private javax.swing.JMenu jMImovel;
    private javax.swing.JMenu jMLocacao;
    private javax.swing.JMenu jMUsuario;
    private javax.swing.JMenu jMVenda;
    private javax.swing.JMenuBar jMenuBarTop;
    // End of variables declaration//GEN-END:variables

    private void cadastroUsuario() {
        UsuarioEditView usuarioEditView = new UsuarioEditView(new JFrame(), true);
        usuarioEditView.setLocationRelativeTo(null);
        usuarioEditView.setVisible(true);
    }

}
