/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import java.awt.Frame;
import javax.swing.JFrame;
import view.cliente.ClienteEditView;
import view.cliente.ClienteQueryView;
import view.imovel.ImovelEditView;
import view.imovel.ImovelQueryView;
import view.usuario.UsuarioEditView;
import view.usuario.UsuarioQueryView;

/**
 *
 * @author marlon e eder
 */
public class Imobiliaria extends javax.swing.JDialog {

    /**
     * Creates new form Imobiliaria
     */
    
    public Imobiliaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLUsuarioLogado = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonConsCliente = new javax.swing.JButton();
        jButtonCadImovel = new javax.swing.JButton();
        jButtonConsImovel = new javax.swing.JButton();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonConsUsuario = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jButtonLocar = new javax.swing.JButton();
        jButtonLocar1 = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();
        jMenuBarTop = new javax.swing.JMenuBar();
        jMCliente = new javax.swing.JMenu();
        jMICadCliente = new javax.swing.JMenuItem();
        jMICadImovel = new javax.swing.JMenuItem();
        jMICadUsuario = new javax.swing.JMenuItem();
        jMImovel = new javax.swing.JMenu();
        jMIConsCliente = new javax.swing.JMenuItem();
        jMIConsImovel = new javax.swing.JMenuItem();
        jMIConsUsuario = new javax.swing.JMenuItem();
        jMUsuario = new javax.swing.JMenu();
        jMIVenderImovel = new javax.swing.JMenuItem();
        jMILocarImovel = new javax.swing.JMenuItem();
        jMLocacao = new javax.swing.JMenu();
        jMIConfiguracao = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMISobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLUsuarioLogado.setToolTipText("Usuário Logado");

        jToolBar1.setRollover(true);

        jButtonCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadCliente.png"))); // NOI18N
        jButtonCadCliente.setToolTipText("Cadastrar um Novo Cliente");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadCliente);

        jButtonConsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consCliente.png"))); // NOI18N
        jButtonConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonConsCliente);

        jButtonCadImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadImovel.png"))); // NOI18N
        jButtonCadImovel.setToolTipText("Cadastrar um Novo Imóvel");
        jButtonCadImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadImovelActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadImovel);

        jButtonConsImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consImovel.png"))); // NOI18N
        jButtonConsImovel.setToolTipText("Pesquisar Dados de Imóvel");
        jButtonConsImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsImovelActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonConsImovel);

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadUsuario.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Cadastrar um Novo Usuário");
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadUsuario);

        jButtonConsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consUsuario.png"))); // NOI18N
        jButtonConsUsuario.setToolTipText("Pesquisar Dados de Usuário");
        jButtonConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonConsUsuario);

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venderImovel.png"))); // NOI18N
        jButtonVenda.setToolTipText("Vender Imóvel");
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonVenda);

        jButtonLocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/locarImovel.png"))); // NOI18N
        jButtonLocar.setToolTipText("Locar Imóvel");
        jButtonLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonLocar);

        jButtonLocar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conf.png"))); // NOI18N
        jButtonLocar1.setToolTipText("Locar Imóvel");
        jButtonLocar1.setFocusable(false);
        jButtonLocar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLocar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLocar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonLocar1);

        jButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        jButtonAjuda.setToolTipText("Ajuda");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAjuda);

        jMCliente.setText("Cadastros");
        jMCliente.setToolTipText("");

        jMICadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadClienteMenu.png"))); // NOI18N
        jMICadCliente.setText("Cliente");
        jMICadCliente.setToolTipText("Cadastrar um Novo Cliente");
        jMICadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadClienteActionPerformed(evt);
            }
        });
        jMCliente.add(jMICadCliente);

        jMICadImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadImovelMenu.png"))); // NOI18N
        jMICadImovel.setText("Imóvel");
        jMICadImovel.setToolTipText("Pesquisar Dados de Clientes");
        jMICadImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadImovelActionPerformed(evt);
            }
        });
        jMCliente.add(jMICadImovel);

        jMICadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMICadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadUsuarioMenu.png"))); // NOI18N
        jMICadUsuario.setText("Usuário");
        jMICadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadUsuarioActionPerformed(evt);
            }
        });
        jMCliente.add(jMICadUsuario);

        jMenuBarTop.add(jMCliente);

        jMImovel.setText("Consultas");

        jMIConsCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMIConsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conClienteMenu.png"))); // NOI18N
        jMIConsCliente.setText("Cliente");
        jMIConsCliente.setToolTipText("Cadastrar um Novo Imóvel");
        jMIConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsClienteActionPerformed(evt);
            }
        });
        jMImovel.add(jMIConsCliente);

        jMIConsImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMIConsImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conImovelMenu.png"))); // NOI18N
        jMIConsImovel.setText("Imóvel");
        jMIConsImovel.setToolTipText("Pesquisar Dados de Imóveis");
        jMIConsImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsImovelActionPerformed(evt);
            }
        });
        jMImovel.add(jMIConsImovel);

        jMIConsUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMIConsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conUsuarioMenu.png"))); // NOI18N
        jMIConsUsuario.setText("Usuário");
        jMIConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsUsuarioActionPerformed(evt);
            }
        });
        jMImovel.add(jMIConsUsuario);

        jMenuBarTop.add(jMImovel);

        jMUsuario.setText("Ações");

        jMIVenderImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMIVenderImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venderImovelMenu.png"))); // NOI18N
        jMIVenderImovel.setText("Vender Imóvel");
        jMIVenderImovel.setToolTipText("Cadastrar um Novo Usuário");
        jMIVenderImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVenderImovelActionPerformed(evt);
            }
        });
        jMUsuario.add(jMIVenderImovel);

        jMILocarImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMILocarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/locarImovelMenu.png"))); // NOI18N
        jMILocarImovel.setText("Locar Imóvel");
        jMILocarImovel.setToolTipText("Pesquisar Dados de Usuários");
        jMILocarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILocarImovelActionPerformed(evt);
            }
        });
        jMUsuario.add(jMILocarImovel);

        jMenuBarTop.add(jMUsuario);

        jMLocacao.setText("Sistema");

        jMIConfiguracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confMenu.png"))); // NOI18N
        jMIConfiguracao.setText("Conf. Sistema");
        jMIConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConfiguracaoActionPerformed(evt);
            }
        });
        jMLocacao.add(jMIConfiguracao);

        jMenuBarTop.add(jMLocacao);

        jMAjuda.setText("Ajuda");

        jMISobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMISobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/helpMenu.png"))); // NOI18N
        jMISobre.setText("Sobre o Sistema");
        jMAjuda.add(jMISobre);

        jMenuBarTop.add(jMAjuda);

        setJMenuBar(jMenuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(jLUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        cadClienteView();
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsClienteActionPerformed
        consClienteView();
    }//GEN-LAST:event_jButtonConsClienteActionPerformed
   
    private void jButtonCadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadImovelActionPerformed
        cadImovelView();
    }//GEN-LAST:event_jButtonCadImovelActionPerformed

    private void jButtonConsImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsImovelActionPerformed
        consImovelView();
    }//GEN-LAST:event_jButtonConsImovelActionPerformed
    
    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
        cadastroUsuario();
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    private void jButtonConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsUsuarioActionPerformed
        consUsuarioView();
    }//GEN-LAST:event_jButtonConsUsuarioActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaActionPerformed
    
    private void jButtonLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLocarActionPerformed
  
    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    private void jMICadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadClienteActionPerformed
        cadClienteView();
    }//GEN-LAST:event_jMICadClienteActionPerformed

    private void jMICadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadImovelActionPerformed
        cadImovelView();
    }//GEN-LAST:event_jMICadImovelActionPerformed
    
    private void jMIConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsClienteActionPerformed
        consClienteView();
    }//GEN-LAST:event_jMIConsClienteActionPerformed

    private void jMIConsImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsImovelActionPerformed
        consImovelView();
    }//GEN-LAST:event_jMIConsImovelActionPerformed

    
    private void jMIVenderImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVenderImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIVenderImovelActionPerformed

    private void jMILocarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILocarImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMILocarImovelActionPerformed

    private void jButtonLocar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocar1ActionPerformed
        confView();
    }//GEN-LAST:event_jButtonLocar1ActionPerformed

    private void jMICadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadUsuarioActionPerformed
        cadUsuarioView();
    }//GEN-LAST:event_jMICadUsuarioActionPerformed

    private void jMIConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsUsuarioActionPerformed
        consUsuarioView();
    }//GEN-LAST:event_jMIConsUsuarioActionPerformed

    private void jMIConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfiguracaoActionPerformed
        confView();
    }//GEN-LAST:event_jMIConfiguracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Imobiliaria dialog = new Imobiliaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                LoginView loginView = new LoginView(new JFrame(), true);
                dialog.setSize(800, 600);
                dialog.setVisible(false);

                loginView.setLocationRelativeTo(null);
                loginView.setVisible(true);
                if (LoginView.isLogin()) {
                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                }
            }
        });
    }
    
    public void cadClienteView(){
        ClienteEditView clienteEditView = new ClienteEditView(new Frame(), true);
        clienteEditView.setLocationRelativeTo(null);
        clienteEditView.setResizable(false);
        clienteEditView.setVisible(true);
    }
    
    public void cadImovelView(){
        ImovelEditView imovelEditView = new ImovelEditView(new Frame(), true);
        imovelEditView.setLocationRelativeTo(null);
        imovelEditView.setResizable(false);
        imovelEditView.setVisible(true);
    }
    
    public void cadUsuarioView(){
        UsuarioEditView usuarioEditView = new UsuarioEditView(new Frame(), true);
        usuarioEditView.setLocationRelativeTo(null);
        usuarioEditView.setResizable(false);
        usuarioEditView.setVisible(true);
    }
    
    public void consClienteView(){
        ClienteQueryView clienteQueryView = new ClienteQueryView(new Frame(), true);
        clienteQueryView.setLocationRelativeTo(null);
        clienteQueryView.setResizable(false);
        clienteQueryView.setVisible(true);
    }
    
    public void consImovelView(){
        ImovelQueryView imovelQueryView = new ImovelQueryView(new Frame(), true);
        imovelQueryView.setLocationRelativeTo(null);
        imovelQueryView.setResizable(false);
        imovelQueryView.setVisible(true);
    }
    
    public void consUsuarioView(){
        UsuarioQueryView usuarioQueryView = new UsuarioQueryView(new Frame(), true);
        usuarioQueryView.setLocationRelativeTo(null);
        usuarioQueryView.setResizable(false);
        usuarioQueryView.setVisible(true);
    }
    
    public void confView(){
        BancoConfigView bancoConfigView = new BancoConfigView(new Frame(), true);
        bancoConfigView.setLocationRelativeTo(null);
        bancoConfigView.setResizable(false);
        bancoConfigView.setVisible(true);
    }
    
    public void helpfView(){
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonCadImovel;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonConsCliente;
    private javax.swing.JButton jButtonConsImovel;
    private javax.swing.JButton jButtonConsUsuario;
    private javax.swing.JButton jButtonLocar;
    private javax.swing.JButton jButtonLocar1;
    private javax.swing.JButton jButtonVenda;
    protected static javax.swing.JLabel jLUsuarioLogado;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMICadCliente;
    private javax.swing.JMenuItem jMICadImovel;
    private javax.swing.JMenuItem jMICadUsuario;
    private javax.swing.JMenuItem jMIConfiguracao;
    private javax.swing.JMenuItem jMIConsCliente;
    private javax.swing.JMenuItem jMIConsImovel;
    private javax.swing.JMenuItem jMIConsUsuario;
    private javax.swing.JMenuItem jMILocarImovel;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenuItem jMIVenderImovel;
    private javax.swing.JMenu jMImovel;
    private javax.swing.JMenu jMLocacao;
    private javax.swing.JMenu jMUsuario;
    private javax.swing.JMenuBar jMenuBarTop;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void cadastroUsuario() {
        UsuarioEditView usuarioEditView = new UsuarioEditView(new JFrame(), true);
        usuarioEditView.setLocationRelativeTo(null);
        usuarioEditView.setVisible(true);
    }

}
