/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cliente;

import control.ClienteController;
import java.awt.Frame;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.cliente.EstadoCivilEnum;
import model.endereco.EnderecoEntity;
import model.endereco.EstadoEnum;
import model.endereco.TipoLogradouroEnum;
import util.MaskUtil;

/**
 *
 * @author eder
 */
public class ClienteEditView extends javax.swing.JDialog {

    /**
     * Creates new form ClienteEdit
     */
    private ClienteController clienteController;
    private MaskUtil mask;
    
    public ClienteEditView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setTitle("..::Tela de Cadastro e Edição de Cliente::..");
        this.clienteController = new ClienteController();
        mask = new MaskUtil();
        initComponents();
        jTFNome.requestFocus();
        applyMask();
    }
    
    public void applyMask(){     
        try {
            mask.maskData(jFTFDataNascimento);  
            mask.maskCpf(JFTFCpf);                  
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Dados inválidos.","Erro",JOptionPane.ERROR_MESSAGE);  
            Logger.getLogger(ClienteEditView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCBEstadoCivil = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFTFRg = new javax.swing.JFormattedTextField();
        jFTFDataNascimento = new javax.swing.JFormattedTextField();
        JFTFCpf = new javax.swing.JFormattedTextField();
        jFTFCelular = new javax.swing.JFormattedTextField();
        jFTFComercial = new javax.swing.JFormattedTextField();
        jFTFResidencial = new javax.swing.JFormattedTextField();
        jFTFFax = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBtipo_logradouro1 = new javax.swing.JComboBox();
        jTFLogradouro1 = new javax.swing.JTextField();
        jTFNumero1 = new javax.swing.JTextField();
        jTFComplemento1 = new javax.swing.JTextField();
        jTFBairro1 = new javax.swing.JTextField();
        jTFMunicipio1 = new javax.swing.JTextField();
        jCBUf1 = new javax.swing.JComboBox();
        jFTFCep1 = new javax.swing.JFormattedTextField();
        jBAddEndereco1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCBtipo_logradouro2 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jTFNumero2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTFComplemento2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFBairro2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTFMunicipio2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jCBUf2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jFTFCep2 = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        jTFLogradouro2 = new javax.swing.JTextField();
        jBAddEndereco2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCBtipo_logradouro3 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jTFNumero3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTFComplemento3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTFBairro3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTFMunicipio3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jCBUf3 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jFTFCep3 = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jTFLogradouro3 = new javax.swing.JTextField();
        jBAddEndereco3 = new javax.swing.JButton();
        jBOk = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jTFNome.setToolTipText("Digite um Nome");
        jTFNome.setName(""); // NOI18N
        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        jLabel3.setText("RG:");

        jLabel4.setText("Data de Nasc :");

        jLabel5.setText("Estado Civil:");

        jCBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getCliente().getEstadoCivil().values()));

        jLabel6.setText("Fax:");

        jLabel7.setText("Residencial:");

        jLabel8.setText("Comercial:");

        jLabel10.setText("Email:");

        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        jLabel11.setText("Celular::");

        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Dados Pessoais");

        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Contato");

        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Endereço");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Logradouro:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 20));

        jLabel18.setText("Número:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel13.setText("Bairro:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel17.setText("Complemento:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel22.setText("Município:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel23.setText("UF:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jCBtipo_logradouro1.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getTipoLogradouro().values()));
        jPanel1.add(jCBtipo_logradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));
        jPanel1.add(jTFLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 360, -1));
        jPanel1.add(jTFNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));
        jPanel1.add(jTFComplemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, -1));
        jPanel1.add(jTFBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, -1));
        jPanel1.add(jTFMunicipio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 380, -1));

        jCBUf1.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getUf().values()));
        jPanel1.add(jCBUf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        try {
            jFTFCep1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFTFCep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        jBAddEndereco1.setText("Adicionar");
        jBAddEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddEndereco1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBAddEndereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jTabbedPane1.addTab("Endereço 01", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBtipo_logradouro2.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getTipoLogradouro().values()));
        jPanel2.add(jCBtipo_logradouro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel24.setText("Número:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel2.add(jTFNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        jLabel25.setText("Complemento:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        jPanel2.add(jTFComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, -1));

        jLabel15.setText("Bairro:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel2.add(jTFBairro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, -1));

        jLabel26.setText("Município:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel2.add(jTFMunicipio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 380, -1));

        jLabel27.setText("UF:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jCBUf2.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getUf().values()));
        jPanel2.add(jCBUf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel16.setText("CEP:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        try {
            jFTFCep2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFTFCep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        jLabel35.setText("Logradouro:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 20));
        jPanel2.add(jTFLogradouro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 360, -1));

        jBAddEndereco2.setText("Adicionar");
        jBAddEndereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddEndereco2ActionPerformed(evt);
            }
        });
        jPanel2.add(jBAddEndereco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jTabbedPane1.addTab("Endereço 02", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBtipo_logradouro3.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getTipoLogradouro().values()));
        jPanel3.add(jCBtipo_logradouro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel29.setText("Número:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel3.add(jTFNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 80, -1));

        jLabel30.setText("Complemento:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        jPanel3.add(jTFComplemento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 300, -1));

        jLabel31.setText("Bairro:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel3.add(jTFBairro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 500, -1));

        jLabel32.setText("Município:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel3.add(jTFMunicipio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 380, -1));

        jLabel33.setText("UF:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jCBUf3.setModel(new javax.swing.DefaultComboBoxModel(this.clienteController.getEndereco().getUf().values()));
        jPanel3.add(jCBUf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel34.setText("CEP:");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        try {
            jFTFCep3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jFTFCep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        jLabel36.setText("Logradouro:");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 20));
        jPanel3.add(jTFLogradouro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 360, -1));

        jBAddEndereco3.setText("Adicionar");
        jBAddEndereco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddEndereco3ActionPerformed(evt);
            }
        });
        jPanel3.add(jBAddEndereco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jTabbedPane1.addTab("Endereço 03", jPanel3);

        jBOk.setText("Ok");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Código:");

        jTFId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(jFTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7)
                                .addGap(3, 3, 3)
                                .addComponent(jFTFResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(jFTFComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)
                                .addComponent(jFTFFax, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addGap(22, 22, 22)
                                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(540, 540, 540)
                                .addComponent(jBOk)
                                .addGap(9, 9, 9)
                                .addComponent(jBFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel4))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel3)
                                        .addGap(26, 26, 26)
                                        .addComponent(jFTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jFTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addGap(19, 19, 19)
                .addComponent(jLabel20)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBOk)
                    .addComponent(jBFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        setCliente();
        setContato();              
        this.clienteController.create();
        ClienteView view = new ClienteView(new Frame(), true);
        dispose();
        view.setLocationRelativeTo(null);
        view.setVisible(true);        
    }//GEN-LAST:event_jBOkActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
    
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jBAddEndereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddEndereco2ActionPerformed
        setEndereco2();        
    }//GEN-LAST:event_jBAddEndereco2ActionPerformed

    private void jBAddEndereco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddEndereco3ActionPerformed
        setEndereco3();  
    }//GEN-LAST:event_jBAddEndereco3ActionPerformed

    private void jBAddEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddEndereco1ActionPerformed
        setEndereco1();
    }//GEN-LAST:event_jBAddEndereco1ActionPerformed

    private void addEndereco(){        
        this.clienteController.getCliente().getEnderecos().add(this.clienteController.getEndereco());
    }
    
    private void setContato(){
        this.clienteController.getCliente().setContato(this.clienteController.getContato());        
    }
    
     private void setCliente() {     
         /*Seta os atributos ClienteEntity*/
        this.clienteController.getCliente().setNome(jTFNome.getText());
        this.clienteController.getCliente().setCpf(JFTFCpf.getText());
        this.clienteController.getCliente().setRg(jFTFRg.getText());
//        this.clienteController.getCliente().setDataNascimento(jFTFDataNascimento.getText());
        this.clienteController.getCliente().setEstadoCivil((EstadoCivilEnum)jCBEstadoCivil.getSelectedItem());
        
        /*Seta os campos ContatoEntity*/
        this.clienteController.getContato().setFoneResidencial(jFTFResidencial.getText());
        this.clienteController.getContato().setFoneComercial(jFTFComercial.getText());
        this.clienteController.getContato().setCelular(jFTFCelular.getText());
        this.clienteController.getContato().setEmail(jTFEmail.getText());
        this.clienteController.getContato().setFax(jFTFFax.getText());        
                  
    }
     
     private void setEndereco1(){
         this.clienteController.newEndereco();
         /*Seta os campos EnderecoEntity Aba 01*/
        this.clienteController.getEndereco().setBairro(jTFBairro1.getText());
//        this.clienteController.getEndereco().setCep(jFTFCep1.getText());
        this.clienteController.getEndereco().setComplemento(jTFComplemento1.getText());
        this.clienteController.getEndereco().setLogradouro(jTFLogradouro1.getText());
        this.clienteController.getEndereco().setMunicipio(jTFMunicipio1.getText());
//        this.clienteController.getEndereco().setNumero(Integer.parseInt(jTFNumero1.getText()));
        this.clienteController.getEndereco().setTipoLogradouro((TipoLogradouroEnum)jCBtipo_logradouro1.getSelectedItem());
        this.clienteController.getEndereco().setUf((EstadoEnum)jCBUf1.getSelectedItem());        
        addEndereco();        
     }
     
     private void setEndereco2(){
         this.clienteController.newEndereco();
         System.out.println("NOVO ENDEREÇO 2 NULL" + this.clienteController.getEndereco().toString());
         /*Seta os campos EnderecoEntity Aba 02*/
        this.clienteController.getEndereco().setBairro(jTFBairro2.getText());
        this.clienteController.getEndereco().setCep(jFTFCep2.getText());
        this.clienteController.getEndereco().setComplemento(jTFComplemento2.getText());
        this.clienteController.getEndereco().setLogradouro(jTFLogradouro2.getText());
        this.clienteController.getEndereco().setMunicipio(jTFMunicipio2.getText());
//        this.clienteController.getEndereco().setNumero(Integer.parseInt(jTFNumero2.getText()));
        this.clienteController.getEndereco().setTipoLogradouro((TipoLogradouroEnum)jCBtipo_logradouro2.getSelectedItem());
        this.clienteController.getEndereco().setUf((EstadoEnum)jCBUf2.getSelectedItem());
        System.out.println("NOVO ENDEREÇO 2 " + this.clienteController.getEndereco().toString());
        addEndereco();      
     }
     
     private void setEndereco3(){
         this.clienteController.newEndereco();
         System.out.println("NOVO ENDEREÇO 3 NULL" + this.clienteController.getEndereco().toString());
          /*Seta os campos EnderecoEntity Aba 03*/
        this.clienteController.getEndereco().setBairro(jTFBairro3.getText());
        this.clienteController.getEndereco().setCep(jFTFCep3.getText());
        this.clienteController.getEndereco().setComplemento(jTFComplemento3.getText());
        this.clienteController.getEndereco().setLogradouro(jTFLogradouro3.getText());
        this.clienteController.getEndereco().setMunicipio(jTFMunicipio3.getText());
//        this.clienteController.getEndereco().setNumero(Integer.parseInt(jTFNumero3.getText()));
        this.clienteController.getEndereco().setTipoLogradouro((TipoLogradouroEnum)jCBtipo_logradouro3.getSelectedItem());
        this.clienteController.getEndereco().setUf((EstadoEnum)jCBUf3.getSelectedItem());
        System.out.println("NOVO ENDEREÇO 3 " + this.clienteController.getEndereco().toString());
        addEndereco();
     }
     
     private void getEndereco1(EnderecoEntity endereco){
        jTFBairro1.setText(endereco.getBairro());
        jFTFCep1.setText(endereco.getCep());
        jTFComplemento1.setText(endereco.getComplemento());
        jTFLogradouro1.setText(endereco.getLogradouro());
        jTFMunicipio1.setText(endereco.getMunicipio());
        jTFNumero1.setText(String.valueOf(endereco.getNumero()));
        jCBtipo_logradouro1.setSelectedItem(endereco.getTipoLogradouro());
        jCBUf1.setSelectedItem(endereco.getUf());
     }
    
     private void getEndereco2(EnderecoEntity endereco){
        jTFBairro2.setText(endereco.getBairro());
        jFTFCep2.setText(endereco.getCep());
        jTFComplemento2.setText(endereco.getComplemento());
        jTFLogradouro2.setText(endereco.getLogradouro());
        jTFMunicipio2.setText(endereco.getMunicipio());
        jTFNumero2.setText(String.valueOf(endereco.getNumero()));
        jCBtipo_logradouro2.setSelectedItem(endereco.getTipoLogradouro());
        jCBUf2.setSelectedItem(endereco.getUf());
     }
     
     private void getEndereco3(EnderecoEntity endereco){
        jTFBairro3.setText(endereco.getBairro());
        jFTFCep3.setText(endereco.getCep());
        jTFComplemento3.setText(endereco.getComplemento());
        jTFLogradouro3.setText(endereco.getLogradouro());
        jTFMunicipio3.setText(endereco.getMunicipio());
        jTFNumero3.setText(String.valueOf(endereco.getNumero()));
        jCBtipo_logradouro3.setSelectedItem(endereco.getTipoLogradouro());
        jCBUf3.setSelectedItem(endereco.getUf());
     }
    
    public void getCliente(){  
        jTFId.setText(ClienteController.getClienteSelecionado().getId().toString());
        jTFNome.setText(ClienteController.getClienteSelecionado().getNome());
        JFTFCpf.setText(ClienteController.getClienteSelecionado().getCpf());
        jFTFRg.setText(ClienteController.getClienteSelecionado().getRg());
//        jFTFDataNascimento.setText(ClienteController.getClienteCurrent().getDataNascimento().toString());
        jCBEstadoCivil.setSelectedItem(ClienteController.getClienteSelecionado().getEstadoCivil().getEstadoCivil());
        
        jFTFResidencial.setText(ClienteController.getClienteSelecionado().getContato().getFoneResidencial());
        jFTFComercial.setText(ClienteController.getClienteSelecionado().getContato().getFoneComercial());
        jFTFCelular.setText(ClienteController.getClienteSelecionado().getContato().getCelular());
        jTFEmail.setText(ClienteController.getClienteSelecionado().getContato().getEmail());
        jFTFFax.setText(ClienteController.getClienteSelecionado().getContato().getFax());
        
         int i = 1;
       for(EnderecoEntity endereco : ClienteController.getClienteSelecionado().getEnderecos()){
           if(i==1){
               getEndereco1(endereco);
           }else if(i==2){
               getEndereco2(endereco);
           }else{
               getEndereco3(endereco);
           }          
           i++;
       }
       
       /*Passa o valor do ClienteCurrent para um Cliente que já foi instanciado
         Pois na hora de persistir ele persiste um Cliente e não um ClienteCurrent 
         (Isso faz acontecer o UPDATE)*/
       this.clienteController.setCliente(ClienteController.getClienteSelecionado());

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JFTFCpf;
    private javax.swing.JButton jBAddEndereco1;
    private javax.swing.JButton jBAddEndereco2;
    private javax.swing.JButton jBAddEndereco3;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBOk;
    private javax.swing.JComboBox jCBEstadoCivil;
    private javax.swing.JComboBox jCBUf1;
    private javax.swing.JComboBox jCBUf2;
    private javax.swing.JComboBox jCBUf3;
    private javax.swing.JComboBox jCBtipo_logradouro1;
    private javax.swing.JComboBox jCBtipo_logradouro2;
    private javax.swing.JComboBox jCBtipo_logradouro3;
    private javax.swing.JFormattedTextField jFTFCelular;
    private javax.swing.JFormattedTextField jFTFCep1;
    private javax.swing.JFormattedTextField jFTFCep2;
    private javax.swing.JFormattedTextField jFTFCep3;
    private javax.swing.JFormattedTextField jFTFComercial;
    private javax.swing.JFormattedTextField jFTFDataNascimento;
    private javax.swing.JFormattedTextField jFTFFax;
    private javax.swing.JFormattedTextField jFTFResidencial;
    private javax.swing.JFormattedTextField jFTFRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTFBairro1;
    private javax.swing.JTextField jTFBairro2;
    private javax.swing.JTextField jTFBairro3;
    private javax.swing.JTextField jTFComplemento1;
    private javax.swing.JTextField jTFComplemento2;
    private javax.swing.JTextField jTFComplemento3;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFLogradouro1;
    private javax.swing.JTextField jTFLogradouro2;
    private javax.swing.JTextField jTFLogradouro3;
    private javax.swing.JTextField jTFMunicipio1;
    private javax.swing.JTextField jTFMunicipio2;
    private javax.swing.JTextField jTFMunicipio3;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNumero1;
    private javax.swing.JTextField jTFNumero2;
    private javax.swing.JTextField jTFNumero3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
