/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.imovel;

import control.ImovelController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marlon e eder
 */
public class ImovelView extends javax.swing.JDialog {

    /**
     * Creates new form ImovelView
     */
    private ImovelController imovelController;
    
    public ImovelView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setTitle("..::Tela de Visualização de Imóvel::..");        
        initComponents();
        this.imovelController = new ImovelController();
        setLabel();
    }
    
    public void setLabel(){
        jLId.setText(ImovelController.getImovelSelecionado().getId().toString());
        jLCliente.setText(ImovelController.getImovelSelecionado().getCliente().getNome());
//        jLCliente.setText(ClienteController.getClienteSelecionado().getNome());
//        jLData.setText(ImovelController.getImovelSelecionado().getData().toString());
        jLLogradouro.setText(ImovelController.getImovelSelecionado().getEndereco().getLogradouro());
        jLNumero.setText(String.valueOf(ImovelController.getImovelSelecionado().getEndereco().getNumero()));
        jLComplemento.setText(ImovelController.getImovelSelecionado().getEndereco().getComplemento()); 
        jLBairro.setText(ImovelController.getImovelSelecionado().getEndereco().getBairro());
        jLCidade.setText(ImovelController.getImovelSelecionado().getEndereco().getMunicipio());
        jLCep.setText(ImovelController.getImovelSelecionado().getEndereco().getCep());
        jLUf.setText(String.valueOf(ImovelController.getImovelSelecionado().getEndereco().getUf()));
        jLNumeroDormitorios.setText(String.valueOf(ImovelController.getImovelSelecionado().getDormitorio()));
        jLModalidade.setText(String.valueOf(ImovelController.getImovelSelecionado().getModalidade()));
        jLTipo.setText(String.valueOf(ImovelController.getImovelSelecionado().getTipo()));
        jLStatus.setText(String.valueOf(ImovelController.getImovelSelecionado().getStatus()));
        jLValor.setText(String.valueOf(ImovelController.getImovelSelecionado().getValor()));
        jTextArea2.setText(ImovelController.getImovelSelecionado().getDescricao());
        
        jLId.setForeground(Color.blue);
        jLCliente.setForeground(Color.blue);
//        jLData.setForeground(Color.blue);      
        jLLogradouro.setForeground(Color.blue);
        jLNumero.setForeground(Color.blue);
        jLComplemento.setForeground(Color.blue);
        jLBairro.setForeground(Color.blue);
        jLCidade.setForeground(Color.blue);
        jLCep.setForeground(Color.blue);
        jLUf.setForeground(Color.blue);
        jLNumeroDormitorios.setForeground(Color.blue);
        jLModalidade.setForeground(Color.blue);
        jLTipo.setForeground(Color.blue);
        jLStatus.setForeground(Color.blue);
        jLValor.setForeground(Color.blue);
        jTextArea2.setForeground(Color.blue);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLCliente = new javax.swing.JLabel();
        jLLogradouro = new javax.swing.JLabel();
        jLNumero = new javax.swing.JLabel();
        jLComplemento = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLCep = new javax.swing.JLabel();
        jLUf = new javax.swing.JLabel();
        jLNumeroDormitorios = new javax.swing.JLabel();
        jLModalidade = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Logradouro:");

        jLabel5.setText("Status:");

        jLabel16.setForeground(new java.awt.Color(47, 145, 249));
        jLabel16.setText("Endereço do Imóvel:");

        jLabel6.setText("Cliente:");

        jLabel3.setText("Núm. Dormitórios: ");

        jLabel4.setText("Modalidade:");

        jLabel1.setText("R$");

        jLabel2.setText("Tipo:");

        jLabel17.setForeground(new java.awt.Color(47, 145, 249));
        jLabel17.setText("Descrição do Imóvel:");

        jLabel9.setText("Complemento:");

        jLabel8.setText("Número:");

        jLabel10.setText("Bairro:");

        jLabel11.setText("Munícipio:");

        jLabel12.setText("CEP:");

        jLabel13.setText("Descrição:");

        jLabel14.setText("UF:");

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLCliente.setForeground(new java.awt.Color(255, 0, 0));
        jLCliente.setText("Sem Informação");
        jLCliente.setToolTipText("Cliente");

        jLLogradouro.setForeground(new java.awt.Color(255, 0, 0));
        jLLogradouro.setText("Sem Informação");
        jLLogradouro.setToolTipText("Logradouro");

        jLNumero.setForeground(new java.awt.Color(255, 0, 0));
        jLNumero.setText("Sem Informação");
        jLNumero.setToolTipText("Número");

        jLComplemento.setForeground(new java.awt.Color(255, 0, 0));
        jLComplemento.setText("Sem Informação");
        jLComplemento.setToolTipText("Complemento");

        jLBairro.setForeground(new java.awt.Color(255, 0, 0));
        jLBairro.setText("Sem Informação");
        jLBairro.setToolTipText("Bairro");

        jLCidade.setForeground(new java.awt.Color(255, 0, 0));
        jLCidade.setText("Sem Informação");
        jLCidade.setToolTipText("Município");

        jLCep.setForeground(new java.awt.Color(255, 0, 0));
        jLCep.setText("Sem Informação");
        jLCep.setToolTipText("CEP");

        jLUf.setForeground(new java.awt.Color(255, 0, 0));
        jLUf.setText("Sem Informação");
        jLUf.setToolTipText("Unidade Federativa");

        jLNumeroDormitorios.setForeground(new java.awt.Color(255, 0, 0));
        jLNumeroDormitorios.setText("Sem Informação");
        jLNumeroDormitorios.setToolTipText("Números de Dormitórios");

        jLModalidade.setForeground(new java.awt.Color(255, 0, 0));
        jLModalidade.setText("Sem Informação");
        jLModalidade.setToolTipText("Modalidade");

        jLValor.setForeground(new java.awt.Color(255, 0, 0));
        jLValor.setText("Sem Informação");
        jLValor.setToolTipText("Tipo");

        jLStatus.setForeground(new java.awt.Color(255, 0, 0));
        jLStatus.setText("Sem Informação");
        jLStatus.setToolTipText("Status");

        jLTipo.setForeground(new java.awt.Color(255, 0, 0));
        jLTipo.setText("Sem Informação");
        jLTipo.setToolTipText("R$");

        jLabel18.setText("Código:");

        jLId.setForeground(new java.awt.Color(255, 0, 0));
        jLId.setText("Sem Informação");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101)
                                                .addComponent(jLabel14))
                                            .addComponent(jLComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLUf))
                                    .addComponent(jLCep, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(12, 12, 12)
                        .addComponent(jButton3))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLNumeroDormitorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLModalidade))
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLStatus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLTipo)
                                    .addComponent(jLValor))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLId)
                    .addComponent(jLabel18))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCliente)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLLogradouro))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLComplemento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLBairro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLCidade)
                            .addComponent(jLabel14)
                            .addComponent(jLUf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLCep)))
                    .addComponent(jLNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLNumeroDormitorios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLModalidade))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLStatus)
                            .addComponent(jLabel1)
                            .addComponent(jLValor)))
                    .addComponent(jLTipo))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja Excluir este Imóvel: " , "Excluir Imóvel", 2);
        if(opcao == 0){
            try{
                try {
                    this.imovelController.delete(ImovelController.getImovelSelecionado());
                    JOptionPane.showMessageDialog(null, "Imóvel Excluído com Sucesso!");
                } catch (RuntimeException ex) {
                    JOptionPane.showMessageDialog(null,"Erro ao Excluir Imóvel!","Erro",JOptionPane.ERROR_MESSAGE); 
                }
                dispose();
            }catch (RuntimeException e){
                JOptionPane.showMessageDialog(null, " Erro ao Deletar Imóvel: ERRO: "+e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImovelEditView imovelEditView = new ImovelEditView(new JFrame(), true);
        dispose();
        imovelEditView.getImovel();
        imovelEditView.setLocationRelativeTo(null);
        imovelEditView.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLLogradouro;
    private javax.swing.JLabel jLModalidade;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLNumeroDormitorios;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLUf;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
