/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.imovel;

import control.ImovelController;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author marlon
 */
public class ImovelView extends javax.swing.JDialog {

    /**
     * Creates new form ImovelView
     */
    public ImovelView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        super.setLocationRelativeTo(null);
        initComponents();
        setLabel();
    }
    
    public void setLabel(){
//        jLCliente.setText(ImovelController.getImovelCurrent().getCliente().toString());
//        jLData.setText(ImovelController.getImovelCurrent().getData().toString());
        jLLogradouro.setText(ImovelController.getImovelCurrent().getEndereco().getLogradouro());
        jLNumero.setText(String.valueOf(ImovelController.getImovelCurrent().getEndereco().getNumero()));
        jLComplemento.setText(ImovelController.getImovelCurrent().getEndereco().getComplemento()); 
        jLBairro.setText(ImovelController.getImovelCurrent().getEndereco().getBairro());
        jLCidade.setText(ImovelController.getImovelCurrent().getEndereco().getCidade());
        jLCep.setText(ImovelController.getImovelCurrent().getEndereco().getCep());
        jLUf.setText(String.valueOf(ImovelController.getImovelCurrent().getEndereco().getUf()));
        jLDormitorio.setText(String.valueOf(ImovelController.getImovelCurrent().getDormitorio()));
        jLModalidade.setText(String.valueOf(ImovelController.getImovelCurrent().getModalidade()));
        jLTipo.setText(String.valueOf(ImovelController.getImovelCurrent().getTipo()));
        jLStatus.setText(String.valueOf(ImovelController.getImovelCurrent().getStatus()));
        jLValor.setText(String.valueOf(ImovelController.getImovelCurrent().getValor()));
        jLDescricao.setText(ImovelController.getImovelCurrent().getDescricao());
        
//        jLCliente.setForeground(Color.red);
//        jLData.setForeground(Color.red);      
        jLLogradouro.setForeground(Color.red);
        jLNumero.setForeground(Color.red);
        jLComplemento.setForeground(Color.red);
        jLBairro.setForeground(Color.red);
        jLCidade.setForeground(Color.red);
        jLCep.setForeground(Color.red);
        jLUf.setForeground(Color.red);
        jLDormitorio.setForeground(Color.red);
        jLModalidade.setForeground(Color.red);
        jLTipo.setForeground(Color.red);
        jLStatus.setForeground(Color.red);
        jLValor.setForeground(Color.red);
        jLDescricao.setForeground(Color.red);   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        jLLogradouro = new javax.swing.JLabel();
        jLNumero = new javax.swing.JLabel();
        jLComplemento = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLCep = new javax.swing.JLabel();
        jLUf = new javax.swing.JLabel();
        jLDormitorio = new javax.swing.JLabel();
        jLModalidade = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jLDescricao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelCliente = new javax.swing.JLabel();
        jLabelDataCadastro = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelComplemento = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelUF = new javax.swing.JLabel();
        jLabelQtdDormitorios = new javax.swing.JLabel();
        jLabelModalidade = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Logradouro:");

        jLabel5.setText("Status:");

        jLabel16.setForeground(new java.awt.Color(47, 145, 249));
        jLabel16.setText("Endereço do Imóvel:");

        jLabel6.setText("Cliente:");

        jLabel15.setText("Data Cadastro:");

        jLabel3.setText("Número de Dormitórios: ");

        jLabel4.setText("Modalidade:");

        jLabel1.setText("R$");

        jLabel2.setText("Tipo:");

        jLabel17.setForeground(new java.awt.Color(47, 145, 249));
        jLabel17.setText("Descrição do Imóvel:");

        jLabel9.setText("Complemento:");

        jLabel8.setText("Número:");

        jLabel10.setText("Bairro:");

        jLabel11.setText("Município");

        jLabel12.setText("CEP:");

        jLabel13.setText("Descrição:");

        jLabel14.setText("UF:");

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelCliente.setForeground(new java.awt.Color(25, 118, 18));
        jLabelCliente.setText("jlabel");
        jLabelCliente.setToolTipText("Cliente");

        jLabelDataCadastro.setForeground(new java.awt.Color(25, 118, 18));
        jLabelDataCadastro.setText("jLabel18");

        jLabelLogradouro.setForeground(new java.awt.Color(25, 118, 18));
        jLabelLogradouro.setText("jLabel18");
        jLabelLogradouro.setToolTipText("Logradouro");

        jLabelNumero.setForeground(new java.awt.Color(25, 118, 18));
        jLabelNumero.setText("jLabel18");
        jLabelNumero.setToolTipText("Número");

        jLabelComplemento.setForeground(new java.awt.Color(25, 118, 18));
        jLabelComplemento.setText("jLabel18");
        jLabelComplemento.setToolTipText("Complemento");

        jLabelBairro.setForeground(new java.awt.Color(25, 118, 18));
        jLabelBairro.setText("jLabel18");
        jLabelBairro.setToolTipText("Bairro");

        jLabelMunicipio.setForeground(new java.awt.Color(25, 118, 18));
        jLabelMunicipio.setText("jLabel18");
        jLabelMunicipio.setToolTipText("Município");

        jLabelCEP.setForeground(new java.awt.Color(25, 118, 18));
        jLabelCEP.setText("jLabel18");
        jLabelCEP.setToolTipText("CEP");

        jLabelUF.setForeground(new java.awt.Color(25, 118, 18));
        jLabelUF.setText("jLabel18");
        jLabelUF.setToolTipText("Unidade Federativa");

        jLabelQtdDormitorios.setForeground(new java.awt.Color(25, 118, 18));
        jLabelQtdDormitorios.setText("jLabel18");
        jLabelQtdDormitorios.setToolTipText("Números de Dormitórios");

        jLabelModalidade.setForeground(new java.awt.Color(25, 118, 18));
        jLabelModalidade.setText("jLabel18");
        jLabelModalidade.setToolTipText("Modalidade");

        jLabelTipo.setForeground(new java.awt.Color(25, 118, 18));
        jLabelTipo.setText("jLabel18");
        jLabelTipo.setToolTipText("Tipo");

        jLabelStatus.setForeground(new java.awt.Color(25, 118, 18));
        jLabelStatus.setText("jLabel18");
        jLabelStatus.setToolTipText("Status");

        jLabelValor.setForeground(new java.awt.Color(25, 118, 18));
        jLabelValor.setText("jLabel18");
        jLabelValor.setToolTipText("R$");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(jLabelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLCliente))
            .addGroup(layout.createSequentialGroup()
                .addGap(562, 562, 562)
                .addComponent(jLData))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addComponent(jLabelDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(jLLogradouro))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel16))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabelLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLNumero))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLComplemento))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addComponent(jLabelComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addComponent(jLabelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addComponent(jLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabelUF))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel12)
                .addGap(24, 24, 24)
                .addComponent(jLabelCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel17))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLBairro))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jLabelQtdDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLCidade))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jLCep)
                .addGap(18, 18, 18)
                .addComponent(jLabelModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLDormitorio))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLModalidade))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipo)
                    .addComponent(jLStatus))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(12, 12, 12)
                .addComponent(jButton3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabelCliente))
                .addComponent(jLCliente)
                .addGap(6, 6, 6)
                .addComponent(jLData)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabelDataCadastro))
                .addGap(29, 29, 29)
                .addComponent(jLLogradouro)
                .addGap(6, 6, 6)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelLogradouro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabelNumero))
                .addGap(12, 12, 12)
                .addComponent(jLNumero)
                .addGap(6, 6, 6)
                .addComponent(jLComplemento)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabelComplemento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabelBairro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabelMunicipio)
                    .addComponent(jLabel14)
                    .addComponent(jLabelUF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabelCEP))
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addGap(6, 6, 6)
                .addComponent(jLBairro)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelQtdDormitorios))
                .addGap(6, 6, 6)
                .addComponent(jLCidade)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLCep)
                    .addComponent(jLabelModalidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelValor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLDormitorio)
                .addGap(12, 12, 12)
                .addComponent(jLModalidade)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTipo)
                        .addGap(12, 12, 12)
                        .addComponent(jLStatus))
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImovelEditView imovelEditView = new ImovelEditView(new JFrame(), true);
        imovelEditView.getImovel();
        imovelEditView.show(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImovelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImovelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImovelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImovelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImovelView dialog = new ImovelView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLComplemento;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLDormitorio;
    private javax.swing.JLabel jLLogradouro;
    private javax.swing.JLabel jLModalidade;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLUf;
    private javax.swing.JLabel jLValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelModalidade;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelQtdDormitorios;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
