/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.cliente;

import entidade.cliente.ClienteEntidade;
import dao.ClienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eder
 */
public class ConsClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditClienteGUI
     */
    public ConsClienteGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jBpesquisar = new javax.swing.JButton();
        jTFCampoPesquisa = new javax.swing.JTextField();
        jBSair = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultadoConsulta = new javax.swing.JTable();
        jBExcluir = new javax.swing.JButton();
        jLNomeCliente = new javax.swing.JLabel();
        jBDescricaoCliente = new javax.swing.JButton();

        setTitle("Pesquisar Cadastro de Cliente");

        jBpesquisar.setText("Pesquisar");
        jBpesquisar.setToolTipText("Pesquisar");
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });

        jTFCampoPesquisa.setToolTipText("Informe um Nome");

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/exit.png"))); // NOI18N
        jBSair.setToolTipText("Sair");
        jBSair.setBorderPainted(false);
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Edit.png"))); // NOI18N
        jBEditar.setToolTipText("Editar");
        jBEditar.setBorderPainted(false);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jTResultadoConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTResultadoConsulta);

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/trash.png"))); // NOI18N
        jBExcluir.setToolTipText("Excluir");
        jBExcluir.setBorderPainted(false);
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLNomeCliente.setText("Nome do Cliente:");

        jBDescricaoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/edit_find.png"))); // NOI18N
        jBDescricaoCliente.setToolTipText("Descrição Cliente");
        jBDescricaoCliente.setBorderPainted(false);
        jBDescricaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescricaoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDescricaoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSair)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jBpesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEditar)
                    .addComponent(jBSair)
                    .addComponent(jBExcluir)
                    .addComponent(jBDescricaoCliente))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisar)
                    .addComponent(jLNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ClienteDAO c = new ClienteDAO();
    ClienteEntidade cliente = new ClienteEntidade();
    List<ClienteEntidade> lista;
    
    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        // TODO add your handling code here:
        String[] columNames = {"id", "Nome", "Cpf", "Cidade"};
        lista = c.consultar(jTFCampoPesquisa.getText().toString());
        if(lista != null){
        jTResultadoConsulta.setModel(new DefaultTableModel(columNames, lista.size()));
        for (int i = 0; i < lista.size(); i++) {
            cliente = lista.get(i);
            jTResultadoConsulta.setValueAt(cliente.getId(), i, 0);
            jTResultadoConsulta.setValueAt(cliente.getNome(), i, 1);
            jTResultadoConsulta.setValueAt(cliente.getCpf(), i, 2);
            jTResultadoConsulta.setValueAt(cliente.getEndereco().getCidade(), i, 3);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Cliente não Cadastrado");
        }
    }//GEN-LAST:event_jBpesquisarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        setarCliente();
        EditClienteGUI edit = new EditClienteGUI();
        edit.recuperarClienteEntidade(cliente);
        edit.inserirCampos();
        edit.setVisible(true);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void setarCliente() {
        int i = jTResultadoConsulta.getSelectedRow();
        String id = jTResultadoConsulta.getValueAt(i, 0).toString();
        cliente = new ClienteEntidade();
        String idCliente = cliente.getId() +"";
        for (int j = 0; j < lista.size(); j++) {
            cliente = lista.get(i);
            if (idCliente.equals(id)) {
                break;
            }
        }
    }

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        int i = jTResultadoConsulta.getSelectedRow();
        String id = jTResultadoConsulta.getValueAt(i, 0).toString();
        c.remover(id);
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBDescricaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescricaoClienteActionPerformed
        // TODO add your handling code here:
        setarCliente();
        DescClienteGUI descricao = new DescClienteGUI();
        descricao.recuperarCliente(cliente);
        descricao.inserirCampos();
        descricao.setVisible(true);
    }//GEN-LAST:event_jBDescricaoClienteActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDescricaoCliente;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JLabel jLNomeCliente;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCampoPesquisa;
    private javax.swing.JTable jTResultadoConsulta;
    // End of variables declaration//GEN-END:variables
}
