/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.cliente;

import entidade.cliente.ClienteEntidade;
import dao.ClienteDAO;
import entidade.cliente.EnderecoEntidade;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eder
 */
public class EditClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form EditClienteGUI
     */
    public EditClienteGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLEmail = new javax.swing.JLabel();
        jLNumero = new javax.swing.JLabel();
        jLRua = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jLCep = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLRg = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLTelefone = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jTFRua = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jCBEstado = new javax.swing.JComboBox();
        jTFNome = new javax.swing.JTextField();
        jLCpf = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jTFCep = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jTFCidade = new javax.swing.JTextField();
        jTFCelular = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jLEstado = new javax.swing.JLabel();
        jTFDataNascimento = new javax.swing.JTextField();
        jLEstadoCIvil = new javax.swing.JLabel();
        jCBEstadoCIvil = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLNome = new javax.swing.JLabel();
        jTFRg = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLDataNascimento = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLCelular = new javax.swing.JLabel();
        jTFBairro = new javax.swing.JTextField();
        JLCidade = new javax.swing.JLabel();

        setTitle("Alterar Cliente");

        jLEmail.setText("E-mail");

        jLNumero.setText("Nº");

        jLRua.setText("Rua");

        jLCep.setText("CEP");
        jLCep.setToolTipText("");

        jLabel11.setText("Dados do Endereço");

        jLRg.setText("RG");

        jLTelefone.setText("Telefone");

        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Floppy.png"))); // NOI18N
        jBSalvar.setToolTipText("Salvar");
        jBSalvar.setBorder(null);
        jBSalvar.setBorderPainted(false);
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Píaui", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins" }));

        jLCpf.setText("CPF");

        jLBairro.setText("Bairro");

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Stop.png"))); // NOI18N
        jBCancelar.setToolTipText("Cancelar");
        jBCancelar.setBorder(null);
        jBCancelar.setBorderPainted(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLEstado.setText("Estado");

        jLEstadoCIvil.setText("Estado Civil");

        jCBEstadoCIvil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro (a)", "Casado (a)", "Divorciado (a)", "Viúvo (a)", "Outro" }));
        jCBEstadoCIvil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadoCIvilActionPerformed(evt);
            }
        });

        jLabel14.setText("Dados do Cliente");

        jLNome.setText("Nome");

        jLabel18.setText("Contato");

        jLDataNascimento.setText("Data Nasc.");

        jLCelular.setText("Celular");

        JLCidade.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLRua)
                        .addGap(65, 65, 65)
                        .addComponent(jTFRua, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLNumero)
                        .addGap(2, 2, 2)
                        .addComponent(jTFNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLNome)
                        .addGap(45, 45, 45)
                        .addComponent(jTFNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLTelefone)
                        .addGap(16, 16, 16)
                        .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLCelular)
                        .addGap(10, 10, 10)
                        .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLEmail)
                        .addGap(37, 37, 37)
                        .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLEstadoCIvil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBEstadoCIvil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCpf)
                                .addGap(54, 54, 54)
                                .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLRg)
                                .addGap(53, 53, 53)
                                .addComponent(jTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLBairro)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLCep)
                                .addGap(32, 32, 32)
                                .addComponent(jTFCep))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jCBEstado, 0, 202, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JLCidade)
                        .addGap(252, 252, 252)
                        .addComponent(jLEstado)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancelar))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLNome))
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCpf)
                            .addComponent(jLRg))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLDataNascimento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstadoCIvil)
                            .addComponent(jCBEstadoCIvil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTFDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRua)
                    .addComponent(jTFRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumero)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLCidade)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEstado)
                        .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBairro)
                    .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCep)
                    .addComponent(jTFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTelefone)
                            .addComponent(jLCelular))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLEmail))
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClienteEntidade cliente;
    
    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        EnderecoEntidade endereco = new EnderecoEntidade();
        endereco.setCep(jTFCep.getText().toUpperCase().trim());
        endereco.setEstado(jCBEstado.getSelectedItem().toString());
        endereco.setCidade(jTFCidade.getText().toUpperCase().trim());
        endereco.setBairro(jTFBairro.getText().toUpperCase().trim());
        endereco.setRua(jTFRua.getText().toUpperCase().trim());
        endereco.setId(cliente.getEndereco().getId());
        String n = jTFNumero.getText();
        int numero = Integer.valueOf(n);
        endereco.setNumero(numero);
        
        cliente.setEndereco(endereco);
        
        DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date date;
        try {
            date = (Date) formatter.parse(jTFDataNascimento.getText());
            cliente.setDataNascimento(date);
        } catch (ParseException ex) {
            Logger.getLogger(CadClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
        }       
        cliente.setNome(jTFNome.getText().toUpperCase().trim());
        cliente.setCpf(jTFCpf.getText().toUpperCase().trim());
        cliente.setRg(jTFRg.getText().toUpperCase().trim());
        cliente.setTelefone(jTFTelefone.getText().toUpperCase().trim());
        cliente.setCelular(jTFCelular.getText().toUpperCase().trim());
        cliente.setEmail(jTFEmail.getText().toUpperCase().trim());
        cliente.setEstadoCivil(jCBEstadoCIvil.getSelectedItem().toString());
        new ClienteDAO().alterar(cliente);
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed

    public void recuperarClienteEntidade(ClienteEntidade cliente) {
        this.cliente = cliente;
    }

    public void inserirCampos() {
        jTFNome.setText(cliente.getNome());
        jTFCpf.setText(cliente.getCpf());
        jTFRg.setText(cliente.getRg());
        jTFTelefone.setText(cliente.getTelefone());
        jTFCelular.setText(cliente.getCelular());
        jTFEmail.setText(cliente.getEmail());
        jCBEstadoCIvil.setSelectedItem(cliente.getEstadoCivil());
        Date data = cliente.getDataNascimento();
        
        String dt = data.toString();
        String[] strings = dt.split("-");       
        dt = strings[1]+"/"+strings[2]+"/"+strings[0];
        jTFDataNascimento.setText(dt);       

        jTFCep.setText(cliente.getEndereco().getCep());
        jCBEstado.setSelectedItem(cliente.getEndereco().getEstado());
        jTFCidade.setText(cliente.getEndereco().getCidade());
        jTFBairro.setText(cliente.getEndereco().getBairro());
        jTFRua.setText(cliente.getEndereco().getRua());
        jTFNumero.setText(cliente.getEndereco().getNumero() + "");
    }

    private void jCBEstadoCIvilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadoCIvilActionPerformed
//         TODO add your handling code here:        
    }//GEN-LAST:event_jCBEstadoCIvilActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLCidade;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox jCBEstado;
    private javax.swing.JComboBox jCBEstadoCIvil;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCpf;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLEstadoCIvil;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JLabel jLRg;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFCep;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFDataNascimento;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFRg;
    private javax.swing.JTextField jTFRua;
    private javax.swing.JTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
}
