/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import control.UsuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import model.usuario.UsuarioEntity;
import model.usuario.UsuarioTableModel;

/**
 *
 * @author eder
 */
public class UsuarioQueryView extends javax.swing.JDialog {

    private UsuarioController usuarioController;
    private List lista;
    private UsuarioTableModel tableModel;

    /**
     * Creates new form UsuarioQueryView
     */
    public UsuarioQueryView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.usuarioController = new UsuarioController();
        this.lista = new ArrayList();
        this.tableModel = new UsuarioTableModel();
        initComponents();
        this.jRBNome.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jTFValorPesquisa = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jBExcluir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jRBNome = new javax.swing.JRadioButton();
        jRBLogin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Cadastro de Usuários");

        jTFValorPesquisa.setToolTipText("Digite um Nome ou Login");

        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small_search.png"))); // NOI18N
        jBPesquisar.setToolTipText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jTablePesquisa.setModel(getUsuarioTableModel());
        jScrollPane1.setViewportView(jTablePesquisa);

        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small_trash.png"))); // NOI18N
        jBExcluir.setToolTipText("Excluir Cadastro");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small_edit.png"))); // NOI18N
        jBEditar.setToolTipText("Editar Cadastro");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small_exit.png"))); // NOI18N
        jBSair.setToolTipText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        buttonGroup.add(jRBNome);
        jRBNome.setText("Nome:");
        jRBNome.setToolTipText("Pesquisar por Nome");
        jRBNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNomeActionPerformed(evt);
            }
        });

        buttonGroup.add(jRBLogin);
        jRBLogin.setText("Login");
        jRBLogin.setToolTipText("Pesquisar por Login");
        jRBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBExcluir)
                        .addGap(24, 24, 24)
                        .addComponent(jBEditar)
                        .addGap(24, 24, 24)
                        .addComponent(jBSair))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRBNome)
                            .addGap(17, 17, 17)
                            .addComponent(jRBLogin)
                            .addGap(23, 23, 23)
                            .addComponent(jTFValorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRBNome)
                        .addComponent(jRBLogin)
                        .addComponent(jTFValorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBExcluir)
                    .addComponent(jBEditar)
                    .addComponent(jBSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public UsuarioTableModel getUsuarioTableModel() {
//        this.lista = this.usuarioController.getUsuarioDao().findAll();
//        tableModel = new UsuarioTableModel(this.lista);
        return tableModel;
    }

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
        if (jRBLogin.isSelected()) {
            this.lista = this.usuarioController.getUsuarioDao().findFilter("login", jTFValorPesquisa.getText());
            this.tableModel = new UsuarioTableModel(lista);
        } else {
            this.lista = this.usuarioController.getUsuarioDao().findFilter("nome", jTFValorPesquisa.getText());
            this.tableModel = new UsuarioTableModel(lista);
        }
        this.jTablePesquisa.setModel(tableModel);
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        UsuarioEditView  view = new UsuarioEditView(new JFrame(), true);
        view.setLocationRelativeTo(null);
        
        int linha = this.jTablePesquisa.getSelectedRow();
        int coluna = Integer.parseInt(jTablePesquisa.getValueAt(linha, 0).toString());
        
        for (int i = 0; i < lista.size(); i++) {
            this.usuarioController.setUsuario((UsuarioEntity) lista.get(i));
            if(this.usuarioController.getUsuario().getId() == coluna)
                break;
        }
        
        view.setUsuarioController(usuarioController);
        view.setVisible(true);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBSairActionPerformed

    private void jRBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBLoginActionPerformed

    private void jRBNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioQueryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioQueryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioQueryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioQueryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsuarioQueryView dialog = new UsuarioQueryView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JRadioButton jRBLogin;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFValorPesquisa;
    private javax.swing.JTable jTablePesquisa;
    // End of variables declaration//GEN-END:variables
}
