/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.imovel;

import control.ClienteController;
import javax.swing.JOptionPane;
import model.cliente.ClienteTableModel;

/**
 *
 * @author marlon e eder
 */
public class ClienteSelectView extends javax.swing.JDialog {

    /**
     * Creates new form ClienteSearch
     */
    
    private ClienteTableModel clienteTableModel;
    private ClienteController clienteController;
            
    public ClienteSelectView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.clienteTableModel = new ClienteTableModel();
        this.clienteController = new ClienteController();
        initComponents();
        jRBCpf.setSelected(true);
        jTFPesquisa.requestFocus();
    }
    
    public ClienteTableModel getClienteTableModel() {
        this.clienteTableModel = new ClienteTableModel(clienteController.findAll());
        return this.clienteTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBSelecionar = new javax.swing.JButton();
        jTFPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRBCpf = new javax.swing.JRadioButton();
        jRBNome = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBSelecionar.setText("Selecionar");
        jBSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelecionarActionPerformed(evt);
            }
        });

        jTable1.setModel(getClienteTableModel());
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRBCpf);
        jRBCpf.setText("Pesquisar por CPF");

        buttonGroup1.add(jRBNome);
        jRBNome.setText("Pesquisar por Nome");

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSelecionar)
                        .addGap(18, 18, 18)
                        .addComponent(jBFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBCpf)
                                .addGap(18, 18, 18)
                                .addComponent(jRBNome)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBCpf)
                    .addComponent(jRBNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSelecionar)
                    .addComponent(jBFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelecionarActionPerformed
        int row = jTable1.getSelectedRow();
        ClienteController.setClienteSelecionado(this.clienteTableModel.getClienteEntity(row));
        dispose();        
    }//GEN-LAST:event_jBSelecionarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jRBCpf.isSelected()){
            this.clienteTableModel = new ClienteTableModel(this.clienteController.getClienteDao().filterByCpf(jTFPesquisa.getText()));
            jTable1.setModel(this.clienteTableModel);
        }else if(jRBNome.isSelected()){
            this.clienteTableModel = new ClienteTableModel(this.clienteController.getClienteDao().filterByNome(jTFPesquisa.getText()));
            jTable1.setModel(this.clienteTableModel);
        }else {
            JOptionPane.showMessageDialog(null, "Por favor Selecione o Tipo da Pesquisa!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBSelecionar;
    private javax.swing.JButton jButton5;
    private javax.swing.JRadioButton jRBCpf;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPesquisa;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
